services:

    koalamonintegration.jserrerscanner.init:
        class: Koalamon\Integration\JsErrorScannerBundle\EventListener\IntegrationListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.integration.init', method: onInit }